# Generated by Django 4.0.4 on 2022-05-07 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('slot', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Maker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Wine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wine_type', models.CharField(max_length=200)),
                ('blend', models.CharField(max_length=200)),
                ('appelation', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('year', models.CharField(max_length=200)),
                ('alcohol', models.CharField(max_length=200)),
                ('acquired', models.DateTimeField(verbose_name='date acquired')),
                ('maker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winecat.maker')),
                ('where', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winecat.location')),
            ],
        ),
    ]
