# Generated by Django 4.0.4 on 2022-05-07 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winecat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wine',
            old_name='appelation',
            new_name='appellation',
        ),
    ]
