# Generated by Django 4.0.4 on 2022-05-19 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winecat', '0002_rename_appelation_wine_appellation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wine',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
