# Generated by Django 4.0.4 on 2022-09-30 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winecat', '0003_alter_wine_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired', models.DateTimeField(verbose_name='date acquired')),
                ('opened', models.DateTimeField(verbose_name='date opened')),
                ('wine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='winecat.wine')),
            ],
        ),
    ]
