# Generated by Django 4.0.4 on 2022-10-18 23:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('winecat', '0004_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='alcohol',
            field=models.CharField(default='NA', max_length=200),
        ),
        migrations.AddField(
            model_name='stock',
            name='vintage',
            field=models.IntegerField(default=0, verbose_name='Vintage'),
        ),
        migrations.AddField(
            model_name='stock',
            name='where',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='winecat.location'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='opened',
            field=models.DateTimeField(blank=True, verbose_name='date opened'),
        ),
    ]
