# Generated by Django 4.0.4 on 2022-10-18 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winecat', '0005_stock_alcohol_stock_vintage_stock_where_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='opened',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date opened'),
        ),
    ]
